VERSION = { 1 }
SETUP_UPDATE_EVERY_CYCLE = { FALSE }
SETUP_UPDATE_WHEN_HALTED = { TRUE }
SETUP_BUFFER_SIZE = { 10000 }
DIGITAL_PIN = { QEA1 } 
DIGITAL_PIN = { QEA2 } 
DIGITAL_PIN = { QEB1 } 
DIGITAL_PIN = { QEB2 } 
